src/Andreitoledo.SGC.Mvc/Models/Base/BaseEntity.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Andreitoledo.SGC.Mvc.Models.Base
{
    public class BaseEntity
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
    }
}

src/Andreitoledo.SGC.Mvc/Models/Conferencia.cs
using Andreitoledo.SGC.Mvc.Models.Base;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Andreitoledo.SGC.Mvc.Models
{
    
    public class Conferencia : BaseEntity
    {
        [Column("trilha")]
        [Required(ErrorMessage = "Digite a trilha da conferência")]
        public string Trilha { get; set; }

        [Column("nome")]
        [Required(ErrorMessage = "Digite o nome da conferência")]
        public string Nome { get; set; }

        [Column("tempo")]
        [Required(ErrorMessage = "Digite o tempo de duração da conferência")]
        public string Tempo { get; set; }
    }
}

src/Andreitoledo.SGC.Mvc/Models/ErrorViewModel.cs
namespace Andreitoledo.SGC.Mvc.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/Andreitoledo.SGC.Mvc/Controllers/ConferenciaController.cs
using Andreitoledo.SGC.Mvc.Models;
using Andreitoledo.SGC.Mvc.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Andreitoledo.SGC.Mvc.Controllers
{
    public class ConferenciaController : Controller
    {
        private readonly IConferenciaRepository _conferenciaRepository;

        public ConferenciaController(IConferenciaRepository conferenciaRepository)
        {
            _conferenciaRepository = conferenciaRepository;
        }

        // Listar Conferencias
        public IActionResult Index()
        {
            List<Conferencia> conferencias = _conferenciaRepository.BuscarTodos();
            return View(conferencias);
        }

        // Adicionar Conferencias
        [Authorize]
        public IActionResult Incluir()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Incluir(Conferencia conferencia)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _conferenciaRepository.Adicionar(conferencia);
                    TempData["MensagemSucesso"] = "Conferência cadastrada com sucesso!";
                    return RedirectToAction("Index");
                }

                return View(conferencia);
            }
            catch (System.Exception erro)
            {

                TempData["MensagemErro"] = $"Ops, não foi possível cadastrar sua conferência, tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }            
        }

        // Editar Conferencias
        [Authorize]
        public IActionResult Editar(int id)
        {
            Conferencia conferencia = _conferenciaRepository.ListarPorId(id);

            return View(conferencia);
        }

        [HttpPost]
        public IActionResult Alterar(Conferencia conferencia)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _conferenciaRepository.Atualizar(conferencia);
                    TempData["MensagemSucesso"] = "Conferência alterada com sucesso!";
                    return RedirectToAction("Index");
                }

                return View("Editar", conferencia);
            }
            catch (System.Exception erro)
            {

                TempData["MensagemErro"] = $"Ops, não foi possível atualizar sua conferência, tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        // Excluir Conferência
        [Authorize]
        public IActionResult ExcluirConfirmacao(int id)
        {
            Conferencia conferencia = _conferenciaRepository.ListarPorId(id);

            return View(conferencia);
        }

        public IActionResult Excluir(int id)
        {
            try
            {
                bool apagado = _conferenciaRepository.Excluir(id);

                if (apagado)
                {
                    TempData["MensagemSucesso"] = "Conferencia deletada com sucesso!";
                }
                else
                {
                    TempData["MensagemErro"] = $"Ops, não foi possível deletar sua conferência!";
                }

                return RedirectToAction("Index");
            }
            catch (System.Exception erro)
            {

                TempData["MensagemErro"] = $"Ops, não foi possível deletar sua conferência, tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }

        }

    }
}

src/Andreitoledo.SGC.Mvc/Controllers/HomeController.cs
using Andreitoledo.SGC.Mvc.Models;
using Andreitoledo.SGC.Mvc.Repository;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Andreitoledo.SGC.Mvc.Controllers
{
    
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        
        public IActionResult Index()
        {
            return View();
        }

        
        public IActionResult Privacy()
        {
            return View();
        }

        
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Andreitoledo.SGC.Mvc/Views/Conferencia/Editar.cshtml
@model Conferencia
@{
    ViewData["Title"] = "Editar Conferências";
}


<h1 class="display-4">Editar Conferência</h1>

<form asp-controller="Conferencia" asp-action="Alterar" method="post">

    <input type="hidden" asp-for="Id"/>
    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome da conferência">
        @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <label for="trilha">Trilha</label>
        <input type="trilha" asp-for="Trilha" class="form-control" placeholder="Digite a trilha da conferência">
        @Html.ValidationMessageFor(model => model.Trilha, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <label for="celular">Tempo</label>
        <input type="text" asp-for="Tempo" class="form-control" placeholder="Digite o tempo da conferência">
        @Html.ValidationMessageFor(model => model.Tempo, "", new { @class = "text-danger" })
    </div>

    <button type="submit" class="btn btn-primary">Salvar</button>
    <a class="btn btn-secondary" asp-controller="Conferencia" asp-action="Index" role="button">Voltar</a>

</form>

src/Andreitoledo.SGC.Mvc/Views/Conferencia/ExcluirConfirmacao.cshtml
@model Conferencia
@{
    ViewData["Title"] = "Listagem de Conferências";
}

<div class="text-center">
    <h3>Realmente deseja apagar a conferência (@Model.Nome)?</h3>
</div>

<a class="btn btn-primary btn-block" role="button" asp-controller="Conferencia" asp-action="Index">Cancelar exclusão</a>
<a class="btn btn-danger btn-block" asp-controller="Conferencia" asp-route-id="@Model.Id" asp-action="Excluir">Confirmar exclusão</a>

src/Andreitoledo.SGC.Mvc/Views/Conferencia/Incluir.cshtml
@model Conferencia
@{
    ViewData["Title"] = "Cadastrar Conferências";
}

<div class="text-center">

    <h1 class="display-4">Cadastrar Conferência</h1>

</div>

    <form asp-controller="Conferencia" asp-action="Incluir" method="post">

        <div class="form-group">
            <label for="nome">Nome</label>
            <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome da conferência">            
            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <label for="trilha">Trilha</label>
            <input type="text" asp-for="Trilha" class="form-control" placeholder="Digite a trilha da conferência">            
            @Html.ValidationMessageFor(model => model.Trilha, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <label for="tempo">Tempo</label>
            <input type="text" asp-for="Tempo" class="form-control" placeholder="Digite o tempo da conferência">
            @Html.ValidationMessageFor(model => model.Tempo, "", new { @class = "text-danger" })
        </div>
        
        <button type="submit" class="btn btn-primary">Salvar</button>
        <a class="btn btn-secondary" asp-controller="Conferencia" asp-action="Index" role="button">Voltar</a>

    </form>

src/Andreitoledo.SGC.Mvc/Views/Conferencia/Index.cshtml
@model List<Conferencia>
@{
    ViewData["Title"] = "Confirma excluir a conferência";
}

<div class="text-center">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Conferencia" asp-action="Incluir">Adicionar nova conferencia</a>
    </div>
    <br />

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" aria-label="Close">X</button>
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" aria-label="Close">X</button>
            @TempData["MensagemErro"]
        </div>
    }

    <br />

    <h1 class="display-4">Listagem de Conferências</h1>

    <table class="table" id="table-conferencias">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Trilha</th>
                <th scope="col">Nome</th>
                <th scope="col">Tempo</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (Conferencia conferencia in Model)
                {
                    <tr>
                        <th scope="row">@conferencia.Id</th>
                        <td>@conferencia.Trilha</td>
                        <td>@conferencia.Nome</td>
                        <td>@conferencia.Tempo</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-primary" asp-route-id="@conferencia.Id" asp-controller="Conferencia" asp-action="Editar">Editar</a>
                                <a role="button" class="btn btn-danger" asp-route-id="@conferencia.Id" asp-controller="Conferencia" asp-action="ExcluirConfirmacao">Excluir</a>
                            </div>
                        </td>
                    </tr>
                }
            }

        </tbody>
    </table>
</div>

src/Andreitoledo.SGC.Mvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página Inicial";
}

<div class="text-center">
    <h1 class="display-4">Bem Vindo !</h1>
    <p>Sistema: Gerenciamento de Coferências</p>    
</div>

src/Andreitoledo.SGC.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Andreitoledo - Gerenciamento de Conferências</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Andreitoledo.SGC.Mvc.styles.css" asp-append-version="true" />
    <link href="https://cdn.datatables.net/v/dt/dt-1.13.4/datatables.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Andreitoledo - Gerenciamento de Conferências</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Conferencia" asp-action="Index">Conferencias</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Andreitoledo.Gerenciamento de Conferências - 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-1.13.4/datatables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>